# Google (GOOGL) Stock Analysis

This Project analyzes Alphabet Inc. (GOOGL) using Python and historical market data from Yahoo Finance. 

## Project Goals
- Analyze historical stock prices and returns 
- Caclulate moving averages and RSI
- Build and backtest trading strategies
- Compare strategy performance against buy-and-hold
- Measure risk using volatility, Sharpe ratio, and maximum drawdown
- Estimate CAPM alpha and beta
- Explore machine learning models for predicting stock direction

In [2]:
%pip install yfinance

Collecting yfinance
  Downloading yfinance-1.7.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.3-cp310-abi3-macosx_11_0_arm64.whl.metadata (17 kB)
Requirement already satisfied: lxml>=4.9.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.3.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.5)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.3.3)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.5.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (5.29.3)
Requirement already satisfied: pytz>=2022.5 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2025.2)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/lib/python3.13/site-packages (from yfinance) (2.32.5)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-17.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2025.11.12)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.5.0)
Downloading yfinance-1.7.0-py3-none-any.whl (149 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 21.8 MB/s  0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.5.1-py3-none-any.whl (193 kB)
Downloading websockets-17.1-cp313-cp313-macosx_11_0_arm64.whl (214 kB)
Installing collected packages: multitasking, websockets, peewee, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [yfinance]4/5 [yfinance]
Successfully installed curl_cffi-0.16.3 multitasking-0.0.13 peewee-4.5.1 websockets-17.1 yfinance-1.7.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

## 1. Historical Stock Data
We begin by downloading historical price data for Alphabet Inc. (GOOGL) using Yahoo Finance.

In [4]:
ticker = 'GOOGL'

data = yf.download(
    ticker,
    start = '2015-01-01',
    end = '2026-09-12',
    progress = False
)

data.head()

Price           Close       High        Low       Open    Volume
Ticker          GOOGL      GOOGL      GOOGL      GOOGL     GOOGL
Date
2015-01-02  26.227924  26.537479  26.145210  26.378985  26480000
2015-01-05  25.728178  26.150658  25.643485  26.109054  41182000
2015-01-06  25.093224  25.814855  25.039237  25.779690  54456000
2015-01-07  25.019424  25.333436  24.945133  25.306692  46918000
2015-01-08  25.106596  25.135817  24.517698  24.839141  73054000

In [5]:
data.shape

(2940, 5)

In [6]:
data.tail()

Price            Close        High         Low        Open    Volume
Ticker           GOOGL       GOOGL       GOOGL       GOOGL     GOOGL
Date
2026-09-04  338.459991  343.529999  337.089996  342.470001  23189300
2026-09-08  338.359985  339.679993  333.220001  335.420013  22915800
2026-09-09  330.649994  331.850006  327.899994  331.649994  33151600
2026-09-10  332.600006  333.230011  327.739990  328.230011  23557600
2026-09-11  338.500000  342.980011  335.029999  335.029999  24677500

## 2. Data Cleaning and Basic Checks
Before analyzing the stock, we check the dataset for missing values and duplicate observations.

In [9]:
print('Missing values:')
print(data.isnull().sum())

print('\nDuplicate rows:')
print(data.duplicated().sum())

Missing values:
Price   Ticker
Close   GOOGL     0
High    GOOGL     0
Low     GOOGL     0
Open    GOOGL     0
Volume  GOOGL     0
dtype: int64

Duplicate rows:
0